title = "STAGING --- Prof. Dr. Barne Kleinen"
baseURL = 'https://bkleinen.github.io/staging/'
[params]
  printEnvironment = true
  environment = 'staging'
  envDescription = 'This site contains unpublished changes.'
  productionSite = 'https://home.htw-berlin.de/~kleinen/'
