
#[markup] # already ias it's in markup.toml, this needs to be replaced:
# https://www.markdownguide.org/tools/hugo/
# https://gohugo.io/getting-started/configuration-markup/#goldmark

defaultMarkdownHandler = 'goldmark'
[highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    tabWidth = 4
    # this setting only takes effect
    # if noClasses=true, otherwise
    # the style sheet is used
    #style = 'friendly'
    style = 'perldoc'
    # style = 'solarized-light'
    #style = 'tango'
    # style = 'solarized-dark'
    noClasses=false
# see https://gohugo.io/content-management/mathematics/   
[goldmark]
    [goldmark.extensions]
      [goldmark.extensions.passthrough]
        enable = true
        [goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['§§', '§§'], ['$', '$']]


    [goldmark.renderer]
      unsafe = false