services:
  webserver:
     image: nginx:latest
     container_name: webserver
     volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
         - ./nginx/templates:/etc/nginx/templates
         - ./container_logs/nginx:/var/log/nginx
         - ./nginx/ssl:/etc/ssl
         - ./public_html:/usr/share/nginx/html
     ports:
         - "80:80"
         - "443:443"
     environment:
        - NGINX_HOST="progwebtec.f4.htw-berlin.de"
        - NGINX_CERT_DIR=/etc/ssl
        - NGINX_CERT=nginx-selfsigned.crt
        - NGINX_KEY=nginx-selfsigned.key
        - NGINX_PUBLIC_HTML=/usr/share/nginx/html #from default.conf
     restart: always

networks:
    cont:
        driver:  bridge
        enable_ipv6: false
