name: Deploy Production / progwebtec.github.io
# git@github.com:progwebtec/progwebtec.github.io.git
on:
  push:
    tags:
      - 'xxxxv*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
      - name: Install Bootstrap with npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          cd hugo
          npm install
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Write gitinfo file
        run: bin/hugo_deployment/gitversion.sh ${{ github.ref }} ${{ github.sha }} "${{ github.workflow }}"
      - name: Build Hugo Site
        run: |
          hugo  --source hugo --minify --environment progwebtec

      - name: Deploy to Production on Github Pages / progwebtec
        uses: peaceiris/actions-gh-pages@v3
        # if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN_PROGWEBTEC }}
          external_repository: progwebtec/progwebtec.github.io
          publish_dir: ./hugo/public
          publish_branch: main
          commit_message: "${{ github.ref }} ${{ github.event.head_commit.message }}"
