name: Check Markdown links

on:
  push:
    branches:
      - 23s_disabled
    tags-ignore:
      - 'v*'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1